# Generated by Django 6.0.5 on 2026-06-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jn', models.IntegerField()),
                ('pname', models.CharField(max_length=50)),
                ('run', models.IntegerField()),
                ('wickets', models.IntegerField()),
            ],
        ),
    ]
