# Generated by Django 4.2.30 on 2026-06-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPLapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
